operation:
  log:
    mode: "NORMAL"
  action:
    normal_delay: 5
    sensor_interrupt_delay: 10
test:
  target:
    name: "SVMotor"
    times: 30
    delay: 3
    state: 1
components:
  button:
    channel: 24
    delay: 1
  bno055_sensor:
    frequency: 5
    interval: 0.5
    acceleration_threshold: 10
    magnetic_threshold: 500
  dc_motor:
    pwm_channel: 12
    in1_channel: 22
    in2_channel: 27
    power: 100
    save_power: 50
    direction: 0.3
  sv_motor:
    channel: 18
    frequency: 50
    angle: 40
  sound:
    file: "tureta.wav"
    volume: 1.0
